version: '3'
services:

  omniscidb:
    image: omnisci/core-os-cpu:v5.5.0
    hostname: omniscidb
    ports:
      - 16274:16274
      - 16278:16278
    volumes:
      - ./omnisci.conf:/omnisci-storage/omnisci.conf
