version: '3'
services:

  omniscidb:
    image: omnisci/core-os-cpu:v5.4.0
    hostname: omniscidb
    ports:
      - 6274:6274
      - 6278:6278
    volumes:
      - ./omnisci.conf:/omnisci-storage/omnisci.conf
