# if you have any conflict issue, try to remove "default" from your ~/.condarc file
name: omnisci

channels:
  - quansight/label/omnisci
  - conda-forge

dependencies:
  - altair
  - arrow-cpp 0.15.0
  - bokeh
  - geoviews
  - quansight/label/omnisci::hvplot
  - holoviews >=1.14.0
  - ibis-framework >=1.4
  - intake >=0.5.3
  - intake-omnisci
  - jaeger
  - jupyterlab >=2.2,<3
  - jupyter-jaeger
  - nodejs >=12,<15
  - notebook
  - omnisci-pytools
  - pandas
  - pip
  # pyarrow 0.15.1 is raising an error: Library not loaded: @rpath/libprotobuf.22.dylib
  - pyarrow 0.15.0
  - pydot
  - pymapd >=0.24
  - pytest
  - python 3.7.*
  - rbc >=0.4
  - pip:
    - ibis-vega-transform
    - nbmake==0.1.post1
