# if you have any conflict issue, try to remove "default" from your ~/.condarc file
name: omnisci

channels:
  - quansight/label/omnisci
  - conda-forge

dependencies:
  # force hvplot from specific channel
  - quansight/label/omnisci::hvplot
  - quansight/label/omnisci::omnisci-datascience-tools
  - pip:
    # for tests
    - nbmake==0.1.post1
