# if you have any conflict issue, try to remove "default" from your ~/.condarc file
name: omnisci

channels:
  - conda-forge

dependencies:
  - altair
  - bokeh
  - geoviews
  - hvplot >=0.7.1
  - holoviews >=1.14.0
  - ibis-framework >=1.4
  - ibis-vega-transform >=5.3.0
  - intake >=0.5.3
  - intake-omnisci
  - jaeger
  - jaeger-browser
  - jupyterlab 3.*
  - jupyter-jaeger >=1.0.4
  - nodejs >=12
  - notebook
  - omnisci-pytools
  - pandas
  - pip
  - pydot
  - pymapd >=0.24
  - pytest
  - python 3.8.*
  - rbc >=0.4
  - pip:
    - nbmake >=0.2.0  # for tests
