name: omnisci

channels:
  - conda-forge

dependencies:
  - altair
  - bokeh
  - geoviews
  - graphviz
  - hvplot
  - ibis-framework
  - jaeger
  - jupyterlab>=2
  - llvmlite>=0.29
  - netifaces
  - nodejs>=12
  - notebook
  - numba
  - omnisci-pytools
  - pip
  - pymapd
  - pytest
  - python=3.7
  - rbc
  - six
  - tblib
  - thriftpy2
  - tornado

  - pip:
    - ibis-vega-transform
