name: omnisci

channels:
  - quansight/label/omnisci
  - conda-forge

dependencies:
  - altair
  - bokeh
  - geoviews
  - graphviz
  - ibis-vega-transform
  - intake
  - jaeger
  - jupyterlab>=2
  - llvmlite>=0.29
  - netifaces
  - nodejs>=12
  - notebook
  - numba
  - omnisci-pytools
  - pip
  - pydot
  - pymapd
  - pytest
  - python=3.7
  - python-graphviz
  - rbc
  - six
  - tblib
  - thriftpy2
  - tornado

  - quansight/label/omnisci::holoviews
  - quansight/label/omnisci::hvplot
  - quansight/label/omnisci::ibis-framework

  - pip:
    - intake-omnisci