{% set name = "omnisci-examples" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: generic
  number: 0

requirements:
  host:
    - git
#   run:
#     - omnisci-datascience-tools

# test:
#   imports:
#     - ibis.backends.omniscidb
#     - pymapd
#     - intake
#     - altair
#     - ibis_vega_transform
#     - geoviews
#     - holoviews
#     - graphviz
#     - pydot

about:
  home: https://github.com/Quansight/omnisci-examples
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: 'OmniSci Example Notebooks'

extra:
  recipe-maintainers:
    - xmnlab
