{% set name = "omnisci-examples" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  noarch: generic
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - git

test:
  commands:
    - test -f ${PREFIX}/opt/omnisci-examples/notebooks/00_Connection_Template.ipynb

about:
  home: https://github.com/Quansight/omnisci-examples
  license: MIT
  license_family: MIT
  license_file: ../LICENSE
  summary: 'OmniSci Example Notebooks'

extra:
  recipe-maintainers:
    - xmnlab
