name: conda-build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  macos:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: [3.7]

    env:
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: omnisci-datascience
        channels: quansight/label/omnisci,conda-forge

    - name: install dependencies
      shell: bash -l {0}
      run: |
        conda install -y conda-build anaconda-client

    - name: run conda build
      shell: bash -l {0}
      run: conda-build conda

    - name: release to the quansight conda channel
      shell: bash -l {0}
      if: startsWith(github.event_name, 'push')
      env:
        ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
      run: |
        anaconda --token $ANACONDA_TOKEN upload \
        --user quansight \
        --label omnisci \
        --skip-existing \
        /usr/share/miniconda/envs/omnisci-datascience/conda-bld/noarch/omnisci-examples-*.tar.bz2
