name: pytest
on:
  pull_request:
    branches:
    - '*'
jobs:
  test_suite:
    name: Pytest on ${{ matrix.python-version }}, ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 45
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        python-version: [3.8]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: omnisci
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          auto-update-conda: false
          # This should match what is specified in the environment.yml channels
          channels: conda-forge

      - name: conda config
        run: conda config --show

      - name: conda list
        run: conda list

      - name: Build the docker image
        run: |
          # force docker-compose installation
          conda install -y docker-compose
          # run docker services
          docker-compose build
          docker-compose up -d
          sleep 5

      - name: show containers
        run: docker ps

      - name: run tests
        run: pytest

      - name: test notebooks
        run: pytest --nbmake -vv
